// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class FranchiseStore
{
    public int StoreId { get; set; }

    public int KitchenId { get; set; }

    public string StoreName { get; set; }

    public string Address { get; set; }

    public virtual CentralKitchen Kitchen { get; set; }

    public virtual ICollection<StoreOrder> StoreOrders { get; set; } = new List<StoreOrder>();
}
