// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class InventoryLocation
{
    public int InventoryLocationId { get; set; }

    public int CentralKitchenId { get; set; }

    public string Name { get; set; }

    public string LocationType { get; set; }

    public string Status { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CentralKitchen CentralKitchen { get; set; }
}
