// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class Recipe
{
    public int RecipeId { get; set; }

    public string RecipeName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }
}
