// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class Shipment
{
    public int ShipmentId { get; set; }

    public int StoreOrderId { get; set; }

    public int CentralKitchenId { get; set; }

    public DateTime? ShipmentDate { get; set; }

    public string DeliveryStatus { get; set; }

    public DateTime? ReceivedDate { get; set; }

    public virtual CentralKitchen CentralKitchen { get; set; }

    public virtual ICollection<ShipmentLine> ShipmentLines { get; set; } = new List<ShipmentLine>();

    public virtual StoreOrder StoreOrder { get; set; }
}
