// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class ShipmentLine
{
    public int ShipmentLineId { get; set; }

    public int ShipmentId { get; set; }

    public int ProductId { get; set; }

    public int? ShippedQuantity { get; set; }

    public int? ReceivedQuantity { get; set; }

    public int? DamagedQuantity { get; set; }

    public virtual Product Product { get; set; }

    public virtual Shipment Shipment { get; set; }
}
