// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class StoreOrder
{
    public int StoreOrderId { get; set; }

    public int CentralKitchenId { get; set; }

    public int FranchiseStoreId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public int? Quantity { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public virtual CentralKitchen CentralKitchen { get; set; }

    public virtual FranchiseStore FranchiseStore { get; set; }

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}
