// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class StoreOrderLine
{
    public int StoreOrderLineId { get; set; }

    public int StoreOrderId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public virtual Product Product { get; set; }

    public virtual StoreOrder StoreOrder { get; set; }
}
