// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendSWP391.Core.Models;

public partial class UserInfo
{
    public string UserId { get; set; }

    public string RoleName { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Location { get; set; }
    public string Token { get; set; }

    public virtual Role RoleNameNavigation { get; set; }
}

