// <auto-generated />
using System;
using BackendSWP391.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendSWP391.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260325010211_FixIngredientCurrentStockPrecision")]
    partial class FixIngredientCurrentStockPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendSWP391.Core.Models.CentralKitchen", b =>
                {
                    b.Property<int>("CentralKitchenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("centralKitchenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CentralKitchenId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("CentralKitchenId")
                        .HasName("PK__CentralK__C1E5E783FE9495EC");

                    b.ToTable("CentralKitchen", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.FranchiseStore", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("store_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<int>("KitchenId")
                        .HasColumnType("int")
                        .HasColumnName("kitchen_id");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("store_name");

                    b.HasKey("StoreId")
                        .HasName("PK__Franchis__A2F2A30C21DEC58E");

                    b.HasIndex("KitchenId");

                    b.ToTable("FranchiseStore", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ingredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<decimal?>("CurrentStock")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("currentStock");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ingredientName");

                    b.Property<int?>("MinStock")
                        .HasColumnType("int")
                        .HasColumnName("minStock");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("StorageCondition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("storageCondition");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.HasKey("IngredientId")
                        .HasName("PK__Ingredie__2753A6C7152CB844");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.InventoryLocation", b =>
                {
                    b.Property<int>("InventoryLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventoryLocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryLocationId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("int")
                        .HasColumnName("centralKitchenID");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryLocationId")
                        .HasName("PK__Inventor__A2A6C2F0FC025C81");

                    b.HasIndex("CentralKitchenId");

                    b.ToTable("InventoryLocation", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("productName");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("productTypeID");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipeID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__2D10D14ACEDA15FA");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("StorageCondition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("storageCondition");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("typeName");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__ProductT__CA28F43E35BBD312");

                    b.ToTable("ProductType", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductionBatch", b =>
                {
                    b.Property<int>("ProductionBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productionBatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionBatchId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("int")
                        .HasColumnName("centralKitchenID");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("completedDate");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("ProductionBatchId");

                    b.HasIndex("CentralKitchenId");

                    b.ToTable("ProductionBatch", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductionBatchLine", b =>
                {
                    b.Property<int>("ProductionBatchLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productionBatchLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionBatchLineId"));

                    b.Property<int?>("ProducedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("producedQuantity");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.Property<int>("ProductionBatchId")
                        .HasColumnType("int")
                        .HasColumnName("productionBatchID");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("int")
                        .HasColumnName("requiredQuantity");

                    b.HasKey("ProductionBatchLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionBatchId");

                    b.ToTable("ProductionBatchLine", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recipeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("recipeName");

                    b.HasKey("RecipeId")
                        .HasName("PK__Recipe__C114EE63FBCAA5D0");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recipeIngredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ingredientID");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipeID");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("int")
                        .HasColumnName("centralKitchenID");

                    b.Property<string>("DeliveryStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("deliveryStatus");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("receivedDate");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("shipmentDate");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("int")
                        .HasColumnName("storeOrderID");

                    b.HasKey("ShipmentId")
                        .HasName("PK__Shipment__47217FE16B7B71B7");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("Shipment", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ShipmentLine", b =>
                {
                    b.Property<int>("ShipmentLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipmentLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentLineId"));

                    b.Property<int?>("DamagedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("damagedQuantity");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.Property<int?>("ReceivedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("receivedQuantity");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipmentID");

                    b.Property<int?>("ShippedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("shippedQuantity");

                    b.HasKey("ShipmentLineId")
                        .HasName("PK__Shipment__32DEEEA9A317585B");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentLine", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreCostRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreCostRecord", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreIngredientStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("StoreId", "IngredientId")
                        .HasDatabaseName("IX_StoreIngredientStock_Store");

                    b.ToTable("StoreIngredientStock", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreOrder", b =>
                {
                    b.Property<int>("StoreOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("storeOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreOrderId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("int")
                        .HasColumnName("centralKitchenID");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deliveryDate");

                    b.Property<int>("FranchiseStoreId")
                        .HasColumnType("int")
                        .HasColumnName("franchiseStoreID");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate");

                    b.Property<int?>("ProductionBatchId")
                        .HasColumnType("int")
                        .HasColumnName("productionBatchID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejectReason");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("StoreOrderId")
                        .HasName("PK__StoreOrd__3353A2C6E34AC3AD");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseStoreId");

                    b.HasIndex("ProductionBatchId");

                    b.ToTable("StoreOrder", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreOrderLine", b =>
                {
                    b.Property<int>("StoreOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("storeOrderLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreOrderLineId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("int")
                        .HasColumnName("storeOrderID");

                    b.HasKey("StoreOrderLineId")
                        .HasName("PK__StoreOrdLine");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("StoreOrderLine", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.FranchiseStore", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.CentralKitchen", "Kitchen")
                        .WithMany("FranchiseStores")
                        .HasForeignKey("KitchenId")
                        .IsRequired()
                        .HasConstraintName("fk_store_kitchen");

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.InventoryLocation", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.CentralKitchen", "CentralKitchen")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("CentralKitchenId")
                        .IsRequired()
                        .HasConstraintName("fk_inventory_kitchen");

                    b.Navigation("CentralKitchen");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Product", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_product_type");

                    b.HasOne("BackendSWP391.Core.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_recipe");

                    b.Navigation("ProductType");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductionBatch", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.CentralKitchen", "CentralKitchen")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("CentralKitchenId")
                        .IsRequired()
                        .HasConstraintName("fk_batch_kitchen");

                    b.Navigation("CentralKitchen");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductionBatchLine", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_batchline_product");

                    b.HasOne("BackendSWP391.Core.Models.ProductionBatch", "ProductionBatch")
                        .WithMany("Lines")
                        .HasForeignKey("ProductionBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batchline_batch");

                    b.Navigation("Product");

                    b.Navigation("ProductionBatch");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.RecipeIngredient", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("fk_ri_ingredient");

                    b.HasOne("BackendSWP391.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ri_recipe");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Shipment", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.CentralKitchen", "CentralKitchen")
                        .WithMany("Shipments")
                        .HasForeignKey("CentralKitchenId")
                        .IsRequired()
                        .HasConstraintName("fk_shipment_kitchen");

                    b.HasOne("BackendSWP391.Core.Models.StoreOrder", "StoreOrder")
                        .WithMany("Shipments")
                        .HasForeignKey("StoreOrderId")
                        .IsRequired()
                        .HasConstraintName("fk_shipment_order");

                    b.Navigation("CentralKitchen");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ShipmentLine", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.Product", "Product")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_line_product");

                    b.HasOne("BackendSWP391.Core.Models.Shipment", "Shipment")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("ShipmentId")
                        .IsRequired()
                        .HasConstraintName("fk_line_shipment");

                    b.Navigation("Product");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreCostRecord", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scr_ingredient");

                    b.HasOne("BackendSWP391.Core.Models.FranchiseStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scr_store");

                    b.Navigation("Ingredient");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreIngredientStock", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sis_ingredient");

                    b.HasOne("BackendSWP391.Core.Models.FranchiseStore", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sis_store");

                    b.Navigation("Ingredient");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreOrder", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.CentralKitchen", "CentralKitchen")
                        .WithMany("StoreOrders")
                        .HasForeignKey("CentralKitchenId")
                        .IsRequired()
                        .HasConstraintName("fk_order_kitchen");

                    b.HasOne("BackendSWP391.Core.Models.FranchiseStore", "FranchiseStore")
                        .WithMany("StoreOrders")
                        .HasForeignKey("FranchiseStoreId")
                        .IsRequired()
                        .HasConstraintName("fk_order_store");

                    b.HasOne("BackendSWP391.Core.Models.ProductionBatch", "ProductionBatch")
                        .WithMany("StoreOrders")
                        .HasForeignKey("ProductionBatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_order_batch");

                    b.Navigation("CentralKitchen");

                    b.Navigation("FranchiseStore");

                    b.Navigation("ProductionBatch");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreOrderLine", b =>
                {
                    b.HasOne("BackendSWP391.Core.Models.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_orderline_product");

                    b.HasOne("BackendSWP391.Core.Models.StoreOrder", "StoreOrder")
                        .WithMany("OrderLines")
                        .HasForeignKey("StoreOrderId")
                        .IsRequired()
                        .HasConstraintName("fk_orderline_order");

                    b.Navigation("Product");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackendSWP391.DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackendSWP391.DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSWP391.DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackendSWP391.DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.CentralKitchen", b =>
                {
                    b.Navigation("FranchiseStores");

                    b.Navigation("InventoryLocations");

                    b.Navigation("ProductionBatches");

                    b.Navigation("Shipments");

                    b.Navigation("StoreOrders");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.FranchiseStore", b =>
                {
                    b.Navigation("StoreOrders");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Product", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.ProductionBatch", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StoreOrders");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("BackendSWP391.Core.Models.StoreOrder", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
